### ISSUE TITLE
sub-03 sessions 8 to 12 missing

### ISSUE THREAD

**Issue by FrancoisPgm** [courtois-neuromod/movie10.fmriprep#1]
For sub-03, sessions 8 to 12 are not present. 
Also for sub-05, ses-006 is missing.

**Comment by bpinsard** [comment]
Should be fixed in #2 , will merge after checking that all is correct.
@emdupre 
As for sub-05, there was no usable ses-006, that index was skipped.

**Comment by emdupre** [comment]
Thank you, @bpinsard !

I'm still having some issues accessing this content. Is it just me ?

I'm able to successfully update the datalad dataset with 

```
datalad update --merge
```

I'm having trouble, though, accessing the updated content, with `datalad install -r $f` failing silently and `datalad get $f` returning:

```
$ datalad get sub-03/ses-012/func/sub-03_ses-012_task-figures01_run-2_desc-confounds_timeseries.tsv
get(error): sub-03/ses-012/func/sub-03_ses-012_task-figures01_run-2_desc-confounds_timeseries.tsv (file) [not available; (Note that these git remotes have annex-ignore set: origin)]
```

Accessing these files in the shell suggests that, indeed, the symlinks aren't fetching correctly :

```
$ less sub-03/ses-012/func/sub-03_ses-012_task-figures02_run-2_desc-confounds_timeseries.tsv
sub-03/ses-012/func/sub-03_ses-012_task-figures02_run-2_desc-confounds_timeseries.tsv: No such file or directory

$ ls -la sub-03/ses-012/func/sub-03_ses-012_task-figures02_run-2_desc-confounds_timeseries.tsv
lrwxr-xr-x  1 emdupre  staff  137 Oct 11 13:27 sub-03/ses-012/func/sub-03_ses-012_task-figures02_run-2_desc-confounds_timeseries.tsv -> ../../../.git/annex/objects/gq/WJ/MD5E-s2665431--181d3c126b17e135e025660fa665f596.tsv/MD5E-s2665431--181d3c126b17e135e025660fa665f596.tsv
```

Any suggestions on how to address this ?

**Comment by emdupre** [comment]
Here's some of my `datalad wtf` in case it helps:

<details>
  <summary>:point_down:</summary>

```
# WTF
## datalad 
  - version: 0.17.5
## dataset 
  - branches: 
    - git-annex@3c6f51f
    - main@880331e
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /Users/emdupre/Desktop/movie10.fmriprep
  - repo: AnnexRepo
## extensions 
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - FsEvents
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.21.1
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.3
    - feed-1.0.1.0
    - ghc-8.6.3
    - http-client-0.5.14
    - persistent-sqlite-2.9.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0
  - local repository version: 8
  - operating system: darwin x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions: 
    - 8
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20210631-g9905ec19a
## location 
  - path: /Users/emdupre/Desktop/movie10.fmriprep
  - type: dataset
## python 
  - implementation: CPython
  - version: 3.9.13
## system 
  - distribution: darwin/21.6.0 12.6/arm64
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - filesystem: 
    - CWD: 
      - path: /Users/emdupre/Desktop/movie10.fmriprep
    - HOME: 
      - path: /Users/emdupre
    - TMP: 
      - path: /var/folders/_h/5_yjn8t51cs21zb_j5p6sqc00000gq/T
  - max_path_length: 295
  - name: Darwin
  - release: 21.6.0
  - type: posix
  - version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
```

</details>
